server:
  port: 8888
  
spring:
  application:
    name: servidor-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vitorcelio/vitorcelio-config-server
          default-label: main
          search-paths:
          - 'saudacoes-servico*'